# Reconciled macOS workstation packages. Homebrew Bundle installs missing
# entries but never removes unrelated packages unless cleanup is explicit.

# Shell and workstation control plane
brew "bash"
brew "chezmoi"
brew "coreutils"
brew "direnv"
brew "git"
brew "gh"
brew "hyperfine"
brew "starship"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# Daily terminal tools
brew "atuin"
brew "bat"
brew "bottom"
brew "duf"
brew "dust"
brew "eza"
brew "fd"
brew "fzf"
brew "git-delta"
brew "jq"
brew "lazygit"
brew "neovim"
brew "procs"
brew "pspg"
brew "ripgrep"
brew "tree-sitter-cli"
brew "shellcheck"
brew "shfmt"
brew "trash-cli"
brew "tree"
brew "wget"
brew "yq"
brew "zoxide"

# Product engineering toolchains
brew "awscli"
brew "go"
brew "gradle"
brew "gradle-completion"
brew "libpq"
brew "node"
brew "openjdk"
brew "rust"
brew "uv"

# GUI and vendor-distributed tools already chosen for this workstation
cask "1password-cli"
cask "android-commandlinetools"
cask "android-platform-tools"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
