live_config_reload = true

[colors.bright]
black = "0x6D7070"
blue = "0x3A5CFF"
cyan = "0x03C89C"
green = "0xB8E466"
magenta = "0xA578EA"
red = "0xFF4352"
white = "0xFEFEF8"
yellow = "0xFFD750"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "0x0d0d0d"
blue = "0x2697FF"
cyan = "0x00c2d3"
green = "0x67d637"
magenta = "0xc870cc"
red = "0xfc3f42"
white = "0xEBEBEB"
yellow = "0xFFC620"

[colors.primary]
background = "0x001529"
foreground = "0xEBEBEB"

[font]
size = 20.0

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300
